MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "output_coco_panoptic_X_152_32x8d/model_final.pth"
  BACKBONE:
    CONV_BODY: "R-152-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    FPN_POST_NMS_PER_BATCH: False
    PRE_NMS_TOP_N_TRAIN: 1000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
  RELATION_ON: True
  SEMANTIC:
    NUM_CLASSES: 54
    CONFIDENCE_THR: 0.6
    OVERLAP_THR: 0.6
    STUFF_AREA_LIMIT: 4096
    COMBINE_METHOD: "RAP"
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
DATALOADER:
  NUM_WORKERS: 0
  SIZE_DIVISIBILITY: 32
SOLVER:
  IMS_PER_BATCH: 12
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.0001
  STEPS: (155000,)
  MAX_ITER: 160000
  CHECKPOINT_PERIOD: 5000
  WARMUP_ITERS: 0
  FINETUNE: True
TEST:
  IMS_PER_BATCH: 1
OUTPUT_DIR: "output_coco_panoptic_X_152_32x8d_relation_finetune/"
